kind = "web"
previewPath = "/"
title = "ZSolutionz"
version = "1.0.0"
id = "artifacts/zsolutionz"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24988

[services.development]
run = "pnpm --filter @workspace/zsolutionz run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/zsolutionz", "run", "build" ]
publicDir = "artifacts/zsolutionz/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24988"
BASE_PATH = "/"
